// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuMMxZQNrqIKyTUiOl4_0fYRn-kem3DFM',
    appId: '1:807892439070:web:e375c65128b8c6d1835e0f',
    messagingSenderId: '807892439070',
    projectId: 'digital-vault-0811',
    authDomain: 'digital-vault-0811.firebaseapp.com',
    storageBucket: 'digital-vault-0811.firebasestorage.app',
    measurementId: 'G-4GH5B55WPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDy77RLHrWYF-f6Uen5Y1VFN5yc1rWMfw',
    appId: '1:807892439070:android:a9cc447c33c0068e835e0f',
    messagingSenderId: '807892439070',
    projectId: 'digital-vault-0811',
    storageBucket: 'digital-vault-0811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRpE5KhQ67KCyQ-XZ7L1Vi7pLBJN6QIDE',
    appId: '1:807892439070:ios:30dc130d9cec7417835e0f',
    messagingSenderId: '807892439070',
    projectId: 'digital-vault-0811',
    storageBucket: 'digital-vault-0811.firebasestorage.app',
    iosBundleId: 'com.digitalvault.digitalVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRpE5KhQ67KCyQ-XZ7L1Vi7pLBJN6QIDE',
    appId: '1:807892439070:ios:30dc130d9cec7417835e0f',
    messagingSenderId: '807892439070',
    projectId: 'digital-vault-0811',
    storageBucket: 'digital-vault-0811.firebasestorage.app',
    iosBundleId: 'com.digitalvault.digitalVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuMMxZQNrqIKyTUiOl4_0fYRn-kem3DFM',
    appId: '1:807892439070:web:8e026ca6e2a347b4835e0f',
    messagingSenderId: '807892439070',
    projectId: 'digital-vault-0811',
    authDomain: 'digital-vault-0811.firebaseapp.com',
    storageBucket: 'digital-vault-0811.firebasestorage.app',
    measurementId: 'G-9ENWTEJSRB',
  );
}
